import facemask from "../assets/images/categories/facemask.jpg";
import serum from "../assets/images/categories/serum.jpg";
import moisturizer from "../assets/images/categories/moisturizer.jpg";
import sunscreen from "../assets/images/categories/sunscreen.jpg";
import bodywash from "../assets/images/categories/bodywash.jpg";
import cleanser from "../assets/images/products/cleanser.jpg";
import retinol from "../assets/images/products/Retinol.jpg";
import rosewater from "../assets/images/products/Rosewater.jpg";

export const productData = [
  {
    id: 1,
    name: "SPF 50 Daily Sunscreen",
    category: "Sunscreen",
    price: 899,
    oldPrice: 1099,
    rating: 4.9,
    reviews: 325,
    badge: "Best Seller",
    stock: "In Stock",
    image: sunscreen,
  },
  {
    id: 2,
    name: "Vitamin C Brightening Serum",
    category: "Serums",
    price: 999,
    oldPrice: 1299,
    rating: 4.8,
    reviews: 280,
    badge: "New",
    stock: "In Stock",
    image: serum,
  },
  {
    id: 3,
    name: "Hydrating Moisturizer",
    category: "Moisturizers",
    price: 799,
    oldPrice: 999,
    rating: 4.9,
    reviews: 210,
    badge: "Popular",
    stock: "In Stock",
    image: moisturizer,
  },
  {
    id: 4,
    name: "Clay Detox Face Mask",
    category: "Face Mask",
    price: 699,
    oldPrice: 899,
    rating: 4.7,
    reviews: 185,
    badge: "Sale",
    stock: "Limited Stock",
    image: facemask,
  },
  {
    id: 5,
    name: "Refreshing Body Wash",
    category: "Body Wash",
    price: 599,
    oldPrice: 749,
    rating: 4.8,
    reviews: 160,
    badge: "Trending",
    stock: "In Stock",
    image: bodywash,
  },

  {
  id: 6,
  name: "Green Tea Purifying Cleanser",
  image: cleanser,
  category: "Cleanser",
  price: 649,
  oldPrice: 799,
  rating: 4.8,
  reviews: 224,
  stock: "In Stock",
  badge: "New",
},
{
  id: 7,
  name: "Retinol Overnight Renewal",
  image: retinol,
  category: "Night Care",
  price: 1199,
  oldPrice: 1499,
  rating: 4.9,
  reviews: 316,
  stock: "Best Seller",
  badge: "Best Seller",
},
{
  id: 8,
  name: "Rose Water Hydrating Toner",
  image: rosewater,
  category: "Toner",
  price: 549,
  oldPrice: 699,
  rating: 4.7,
  reviews: 187,
  stock: "In Stock",
  badge: "Trending",
},
];